/* ═══════════════════════════════════════════════════════════════
   Montisoro — TEST report · narrative content (EN)
   English translation of the briefing (14/06/2026). Per absence type
   3 variants; the report shows one based on the entered figures vs.
   the benchmark:  under = better · equal = on par · above = above.
   Benchmarks: short 3.3% · medium 1.9% · long 1.4%
═══════════════════════════════════════════════════════════════ */
window.__TESTREPORT_CONTENT_EN = (function(){
  function analyse(t){return '<div class="sub-h">Analysis</div><p class="p">'+t+'</p>';}
  function bullets(title,arr){return (title?'<p class="p">'+title+'</p>':'')+'<ul class="clean">'+arr.map(function(b){return '<li>'+b+'</li>';}).join('')+'</ul>';}
  function aandacht(t){return '<div class="sub-h">Point of attention</div><p class="p">'+t+'</p>';}
  function doel(t){return '<div class="sub-h">Objective</div><p class="p">'+t+'</p>';}
  function doelen(arr){return '<div class="sub-h">Objectives</div>'+bullets('',arr);}
  function risico(t){return '<div class="sub-h">Risk if no action is taken</div><p class="p">'+t+'</p>';}
  function acties(inner){return '<div class="sub-h">Recommended actions</div>'+inner;}
  function group(title,arr,note){return '<p class="p" style="margin-bottom:2px;"><strong>'+title+'</strong></p>'+(note?'<p class="p" style="margin:0 0 2px;font-style:italic;">'+note+'</p>':'')+'<ul class="clean">'+arr.map(function(b){return '<li>'+b+'</li>';}).join('')+'</ul>';}
  function monitoring(arr){return '<div class="sub-h">Monitoring</div>'+bullets('Progress can be tracked structurally through:',arr);}
  function prio(t){return '<div class="prionote">'+t+'</div>';}

  return {
    /* ───────── SHORT-TERM ABSENCE (benchmark 3.3%) ───────── */
    K:{
      under:
        analyse('Your short-term absence is below the sector average. This points to a strong operational foundation and an effective control of short-duration absences.')+
        bullets('Organisations that perform sustainably better on short-term absence are typically characterised by:',['Consistent follow-up of absences and a deliberate return-to-work policy.','Managers who detect signals early and make them discussable.','Sufficient flexibility to absorb temporary reduced deployability.','An organisational culture in which engagement, responsibility and wellbeing reinforce one another.'])+
        aandacht('A favourable result today is no guarantee for tomorrow. Keeping absence figures low requires continued attention to leadership, work organisation, psychosocial wellbeing and sustainable employability.')+
        acties(bullets('',['Safeguard successful practices around attendance and return-to-work policy.','Document and share successful approaches between teams and departments.','Monitor differences between departments to detect deviations in time.','Anchor absence prevention structurally within the wellbeing, leadership and HR policy.']))+
        doel('Maintain the current strong position with short-term absence below 3.0%.')+
        monitoring(['Real-time absence and wellbeing data via the Storm platform.','Continuous development of managers within the Culture of Care &amp; Capability programme (COCC).','Support for managers, HR and other involved stakeholders via Casey AI.']),
      equal:
        analyse('Your short-term absence is at the level of the sector average. This means your organisation performs as expected within the current market context. There are no direct signals of elevated risk, but at the same time there is little buffer should absence pressure increase.')+
        bullets('Organisations that perform around the sector average are typically characterised by:',['A basic approach to following up absences and return to work.','Managers who follow up on absence, but not always in a consistent manner.','A limited number of preventive initiatives around wellbeing and sustainable employability.','Differences between departments that are not always followed up systematically.'])+
        aandacht('A result at benchmark level provides stability, but no competitive advantage. Without targeted attention to prevention and leadership, there is a risk that short-term absence gradually rises and causes additional costs. The greatest opportunity lies not in reducing a problem, but in creating a structural lead over the benchmark.')+
        acties(bullets('',['Strengthen managers in detecting and discussing signals early.','Increase awareness around attendance, deployability and return to work.','Analyse differences between departments, teams and roles to make local risks visible.','Anchor prevention and wellbeing structurally within daily operations.']))+
        doel('Maintain the current level with an ambition to grow towards short-term absence below the sector average of 3.3%.')+
        monitoring(['Monthly absence and wellbeing reporting via the Storm platform.','Monitoring of trends and deviations at department level.','Automatic alerting when short-term absence evolves towards 4.0% or higher.','Support for managers, employees and HR via Casey AI.']),
      above:
        analyse('Your short-term absence is above the sector average. Although this does not necessarily indicate a structural problem, it is an important signal that warrants further attention. An elevated short-term absence may point to underlying factors that influence the presence and deployability of employees. If these signals are insufficiently followed up, there is a risk that short-duration absences evolve into more frequent or longer-term absence.')+
        bullets('Factors that are often associated with elevated short-term absence are:',['Increased workload or an unbalanced distribution of tasks.','Challenges within team dynamics, leadership or working climate.','Working conditions that increase physical or mental strain.','Role-, department- or season-related factors that may disproportionately affect certain groups.','Insufficient attention to early detection and preventive follow-up.'])+
        aandacht('Short-term absence is often the first visible indicator of broader wellbeing or organisational issues. A rising trend therefore warrants swift analysis and targeted follow-up, so that underlying causes can be addressed in time. The earlier signals are detected, the greater the chance of preventing further escalation and additional costs.')+
        acties(bullets('',['Carry out a targeted analysis of the main absence drivers within the organisation.','Strengthen the conversation skills of managers around attendance, wellbeing and deployability.','Analyse differences between departments, roles and teams to identify local risks.','Increase the focus on prevention, early detection and sustainable employability.','Make absence discussable from a place of support and engagement, rather than control.']))+
        doel('Reduce short-term absence step by step towards the sector average of 3.3% within a period of 6 to 12 months.')+
        monitoring(['Absence analyses per department, team and role via the Storm platform.','Monitoring of trends, frequency absence and recurring patterns.','Early detection of risk signals and precursors via Casey AI.','Periodic evaluation of the impact of preventive and managerial interventions.'])
    },

    /* ───────── MEDIUM-TERM ABSENCE (benchmark 1.9%) ───────── */
    M:{
      under:
        analyse('Your medium-term absence is below the sector average. This points to a strong capacity to successfully support employees during absences of one to twelve months and to reintegrate them in a sustainable way.')+
        bullets('Organisations that perform strongly on medium-term absence are typically characterised by:',['A structured approach to absence and reintegration support.','Timely follow-up of employees during their absence.','Sufficient flexibility in tasks, roles and work organisation upon return.','Close collaboration between managers, HR and other involved stakeholders.','A culture in which contact and engagement are maintained during the absence period.'])+
        aandacht('A strong performance on medium-term absence is often the result of consistent processes and quality follow-up. To preserve this advantage, it is important not to make successful working methods dependent on individuals, but to anchor them structurally within the organisation. In addition, differences between departments can offer valuable insights into which approaches are most effective.')+
        acties(bullets('',['Document and standardise absence and reintegration processes.','Strengthen managers, HR or other involved stakeholders in their role in supporting medium-term absent employees.','Analyse which departments or teams perform above average and share these good practices organisation-wide.','Anchor the principles of Culture of Care &amp; Capability further in daily operations.','Use data and insights to make successful approaches scalable across the entire organisation.']))+
        doel('Maintain the current strong position, with an ambition to optimise medium-term absence further towards 1.5% to 1.7%.')+
        monitoring(['Absence and reintegration analyses per department via the Storm platform.','Benchmarking of departments and teams to make successful practices visible.','Early detection of risks and signals that may lead to longer-term absence via Casey AI.','Periodic evaluation of the effectiveness of reintegration and support processes.']),
      equal:
        analyse('Your medium-term absence is at the level of the sector average. Although this result in itself gives no cause for concern, it is precisely in this absence category that the greatest opportunity often lies to structurally influence both absence duration and absence costs. Medium-term absence is a crucial phase in the absence process. In this period it is often decided whether employees return to work successfully, or evolve towards long-term absence.')+
        bullets('Organisations that perform better than the benchmark typically distinguish themselves through:',['A structured and consistent case management approach.','Clear ownership of absence files.','Regular and constructive contact during the absence period.','Timely assessment of work capacity and reintegration options.','Flexibility in tasks, roles and work organisation.'])+
        aandacht('A benchmark result provides stability, but leaves room for considerable improvement. Small optimisations in the support of employees can have a disproportionately large impact on both the absence duration and the total absence cost. The greatest gain often lies not in extra interventions, but in a more structured and consistent application of existing processes.')+
        acties(
          group('1. Strengthen case management',['Assign one clear case manager (internal or external) per absence file.','From the first weeks, systematically assess work capacity and possible return scenarios.','Ensure regular contact moments during the absence period.','Facilitate workplace and task adjustments where this can support the return.'])+
          group('2. Strengthen leadership and support',['Invest in targeted development of managers via the Culture of Care &amp; Capability programme.','Focus primarily on departments where medium-term absence occurs above average.','Increase the quality of conversations around deployability, recovery and reintegration. Involve the various stakeholders in this as well.'])+
          group('3. Enable data-driven follow-up',['Systematically track trends, lead times and risk profiles.','Use insights to deploy interventions where the impact is greatest.','Combine operational follow-up with predictive insights.'])
        )+
        doel('Reduce medium-term absence from 1.9% to 1.5%. This improvement can lead to a considerable reduction of the absence cost and a higher sustainable employability of employees.')+
        risico('Without targeted follow-up, there is a risk that medium-term absence rises further towards 2.3% to 2.5%, with a considerable impact on both operational continuity and total absence costs.')+
        monitoring(['Real-time absence and reintegration data via the Storm platform.','Predictive alerting of risks and escalations via Casey AI.','Periodic review of ongoing absence files and reintegration trajectories.','Follow-up of results per department, team and manager.'])+
        prio('<b>Priority 1.</b> Medium-term absence offers the highest return on investment in most organisations. Targeted improvements in this category often deliver the fastest and most sustainable impact on both absence figures and cost control.'),
      above:
        analyse('Your medium-term absence is above the sector average. This is an important point of attention, as this absence category often forms the transition between short-duration absence and long-term absence. An elevated medium-term absence indicates that employees return to work less quickly than expected, or that reintegration trajectories have insufficient effect. Without targeted interventions, there is a risk that part of these files evolves into long-term absence, with a considerable impact on costs, productivity and staff availability.')+
        bullets('Organisations confronted with elevated medium-term absence often recognise one or more of the following factors:',['Insufficiently structured case management.','Unclear ownership of absence files.','Limited follow-up during the absence period.','Late assessment of work capacity and reintegration options.','Insufficient use of task, schedule or workplace adjustments.','Managers who are insufficiently supported in guiding absent employees.'])+
        aandacht('This is the absence category with the greatest impact on future long-term absences. Every month that an employee remains absent longer typically lowers the chance of a successful and sustainable return. Early intervention, consistent follow-up and clear direction are therefore crucial to prevent escalation into long-term absence.')+
        acties(
          group('1. Strengthen the diagnostic phase',['Systematically analyse why employees remain absent longer than expected.','Map out the barriers to return to work.','Assess which work and task adjustments have already been examined or applied.','Identify recurring patterns per department, role or manager.'])+
          group('2. Structure case management',['Assign one clear case manager (internal or external) per absence file.','Actively assess work capacity and possible return scenarios.','Ensure regular contact moments throughout the entire absence period.','Make task, workplace and schedule adjustments a fixed part of every reintegration trajectory.'])+
          group('3. Strengthen leadership and support',['Invest primarily in the Culture of Care &amp; Capability programme.','Support managers in holding connecting conversations around deployability and return to work.','Make the distinction clear between supporting, guiding and exerting unwanted pressure.'])+
          group('4. Steer on data and early detection',['Monitor absence trends on a weekly basis.','Detect signals of escalation towards long-term absence early.','Systematically evaluate the effectiveness of interventions and adjust where necessary.'])
        )+
        doel('Reduce medium-term absence towards the sector average of 1.9%. This improvement can lead to a considerable cost saving and a noticeable decrease in the risk of long-term dropout.')+
        risico('If no targeted measures are taken, there is a risk that medium-term absence rises further and a larger share of employees flows through to long-term absence. This not only causes higher absence costs, but also increases the pressure on teams, managers and operational processes.')+
        monitoring(['Weekly follow-up of absence figures and trends via the Storm platform.','Early detection and risk alerting via Casey AI.','Periodic reviews of files on a 30-, 60- and 90-day basis.','Follow-up of results per department, role and manager.'])+
        prio('<b>Priority 1 — critical.</b> Medium-term absence is one of the strongest predictors of future long-term absence. A targeted approach in this phase typically delivers the highest impact, both on absence reduction and on cost control. It therefore warrants immediate and structural attention from HR, managers and management.')
    },

    /* ───────── LONG-TERM ABSENCE (benchmark 1.4%) ───────── */
    L:{
      under:
        analyse('Your long-term absence is below the sector average. This points to a strong control of long-term absences and an effective approach to preventing employees from dropping out for the long term.')+
        bullets('Organisations that perform sustainably better on long-term absence are typically characterised by:',['Strong follow-up of medium-term absence files and reintegration trajectories.','Sufficient flexibility in roles, tasks and work organisation.','A culture in which sustainable employability is central.','Good collaboration between managers, HR, prevention and external partners.','Timely support of employees before problems escalate into long-term dropout.'])+
        aandacht('A low long-term absence is often the result of processes built up over years and a strong preventive approach. Maintaining this position requires continued attention to reintegration, sustainable work and early intervention. In addition, it remains important to actively support employees who are already on long-term absence. The greatest chance of a successful return to work typically lies within the first year of absence.')+
        acties(bullets('',['Keep investing in the successful approach to medium-term absence to prevent flow-through into long-term absence.','Provide individual reintegration trajectories for employees who are already on long-term absence.','Explore options for job crafting, adapted tasks and phased return to work.','Assess alternative roles or forms of work where a return to the original function proves not feasible.','Work together with external partners to maximally support sustainable return trajectories.']))+
        doelen(['Maintain long-term absence below the sector average of 1.4%.','Increase the reactivation rate of existing long-term files.','Prevent medium-term absence from evolving into long-term absence.'])+
        monitoring(['Analysis of file duration, returns to work and task adjustments via the Storm platform.','Follow-up of individual action plans and reintegration trajectories.','Monitoring of the flow-through from medium-term to long-term absence.','Evaluation of outflow and exit patterns to better understand structural causes.','Early detection of risks via Casey AI.'])+
        prio('<b>Priority 3 — consolidate and maintain.</b> The results show that the current approach works effectively. The focus is therefore not on far-reaching corrections, but on maintaining successful practices, optimising existing long-term files and preventing future inflow from medium-term absence.'),
      equal:
        analyse('Your long-term absence is at the level of the sector average. Although this result gives no direct cause for concern, this absence category warrants particular attention because of its major impact on costs, deployability and staff availability. Long-term absence is often the end result of a process that begins months earlier. The longer an employee remains absent, the smaller the chance of a successful and sustainable return to work typically becomes. Organisations that keep long-term absence under control therefore invest not only in supporting existing files, but above all in preventing new inflow.')+
        aandacht('The first twelve months of long-term absence typically form the most crucial period for reintegration. Active support, adapted work options and a realistic return strategy can still make a considerable difference in this phase. In addition, medium-term absence remains the most important predictor of future long-term dropout. A strong approach to medium-term files is therefore the most effective form of prevention.')+
        acties(
          group('1. Strengthen the approach to existing long-term files',['Provide active follow-up of employees on long-term absence. Appoint a case manager (internal or external) for this.','Explore options for job crafting and adapted functions.','Facilitate part-time or phased return to work where possible.','Assess alternative tasks, roles or forms of work.','Make use of external support and specialised guidance where this can accelerate the return.'])+
          group('2. Prevent inflow from medium-term absence',['Strengthen the follow-up of employees in the medium-term absence phase.','Detect files with an elevated risk of long-term dropout early.','Act more quickly on work capacity, task adjustments and reintegration options.','Anchor ownership and follow-up within the case management process.'])
        )+
        doelen(['Maintain long-term absence at or below the sector average of 1.4%.','Increase the reactivation of existing long-term files.','Prevent additional inflow from medium-term absence.'])+
        monitoring(['Analysis of file duration and absence trends via the Storm platform.','Follow-up of individual action plans and reintegration trajectories.','Monitoring of the flow-through from medium-term to long-term absence.','Evaluation of closed files and exit analyses to identify learning points.','Early detection of risk signals via Casey AI.'])+
        prio('<b>Priority 2 — active control.</b> Although long-term absence is at benchmark level, this category requires continued attention. The greatest impact is achieved by actively supporting existing files and preventing employees from flowing through from medium-term to long-term absence. This is where the key to sustainable control of future absence costs lies.'),
      above:
        analyse('Your long-term absence is above the sector average. This is an important challenge, as long-term absences typically have the greatest impact on absence costs, productivity, staff planning and operational continuity. An elevated long-term absence rarely arises suddenly. In most cases it is the result of underlying processes that were insufficiently interrupted during earlier absence phases. It is therefore essential not only to manage the current long-term files, but also to thoroughly analyse the causes of the inflow.')+
        bullets('Organisations with elevated long-term absence are often confronted with one or both of the following situations:',['Insufficient control of medium-term absence, causing employees to flow through to long-term absence.','Complex long-term files in which medical, psychosocial or organisational factors hamper a successful return.'])+
        aandacht('The strongest predictor of future long-term absence is an elevated medium-term absence. The greatest lever therefore often lies not in managing existing long-term files, but in preventing new inflow. At the same time, swift action remains crucial for employees who are already on long-term absence. The chance of a successful return to work typically decreases as the duration of absence increases.')+
        acties(
          group('Route 1 — Strengthen the approach to medium-term absence',['Analyse the flow-through from medium-term to long-term absence.','Strengthen case management and file follow-up.','Facilitate faster task, role and workplace adjustments.','Detect files with an elevated risk of escalation.','Anchor ownership and follow-up within the entire reintegration process.'],'This is the most important priority.')+
          group('Route 2 — Activate existing long-term files',['Analyse the main causes of long-term absence.','Prioritise files within the first year of absence.','Explore options for job crafting and alternative functions.','Facilitate phased or part-time return to work where feasible.','Deploy external expertise and specialised guidance in a targeted way.'])
        )+
        doel('Reduce long-term absence towards the sector average of 1.4% within a period of 6 to 12 months. This improvement can have a considerable impact on both absence costs and staff availability.')+
        risico('If no targeted measures are taken, there is a risk of a further rise in long-term absence. This can lead to a negative spiral of higher costs, increasing workload, more replacement needs and additional inflow from medium-term absence.')+
        monitoring(['Weekly follow-up of long-term files via the Storm platform.','Analysis of the flow-through from medium-term to long-term absence.','Monitoring of file duration, reintegration chances and returns to work.','Early detection of risk signals via Casey AI.','Periodic case reviews and evaluation of ongoing interventions.'])+
        prio('<b>Priority 1 — urgent.</b> An elevated long-term absence requires immediate attention from HR, managers and management. The combination of a strong medium-term approach and an active reintegration strategy for existing files offers the greatest chance of sustainable improvement and cost reduction.')
    }
  };
})();
