/* ═══════════════════════════════════════════════════════════════
   Montisoro — TEST-rapport · narratieve content (briefing 14/06/2026)
   Per verzuimtype 3 varianten; in het rapport wordt er één getoond
   op basis van de ingegeven cijfers t.o.v. de benchmark:
     under = beter dan benchmark · equal = gelijk · above = boven
   Benchmarks: kort 3,3% · middellang 1,9% · langdurig 1,4%
   Tekst = briefing-PDF 14/06/2026 verbatim (klantfeedback verwerkt).
═══════════════════════════════════════════════════════════════ */
window.__TESTREPORT_CONTENT = (function(){
  function analyse(t){return '<div class="sub-h">Analyse</div><p class="p">'+t+'</p>';}
  function bullets(title,arr){return (title?'<p class="p">'+title+'</p>':'')+'<ul class="clean">'+arr.map(function(b){return '<li>'+b+'</li>';}).join('')+'</ul>';}
  function aandacht(t){return '<div class="sub-h">Aandachtspunt</div><p class="p">'+t+'</p>';}
  function doel(t){return '<div class="sub-h">Doelstelling</div><p class="p">'+t+'</p>';}
  function doelen(arr){return '<div class="sub-h">Doelstellingen</div>'+bullets('',arr);}
  function risico(t){return '<div class="sub-h">Risico bij uitblijven van actie</div><p class="p">'+t+'</p>';}
  function acties(inner){return '<div class="sub-h">Aanbevolen acties</div>'+inner;}
  function group(title,arr,note){return '<p class="p" style="margin-bottom:2px;"><strong>'+title+'</strong></p>'+(note?'<p class="p" style="margin:0 0 2px;font-style:italic;">'+note+'</p>':'')+'<ul class="clean">'+arr.map(function(b){return '<li>'+b+'</li>';}).join('')+'</ul>';}
  function monitoring(arr){return '<div class="sub-h">Monitoring</div>'+bullets('De voortgang kan structureel worden opgevolgd via:',arr);}
  function prio(t){return '<div class="prionote">'+t+'</div>';}

  return {
    /* ───────── KORT VERZUIM (benchmark 3,3%) ───────── */
    K:{
      under:
        analyse('Het kort verzuim binnen uw organisatie ligt onder het sectorgemiddelde. Dit wijst op een sterke operationele basis en een effectieve beheersing van kortdurende afwezigheden.')+
        bullets('Organisaties die duurzaam beter presteren op het vlak van kort verzuim kenmerken zich doorgaans door:',['Een consequente opvolging van afwezigheden en een doordacht terugkeerbeleid.','Leidinggevenden die signalen vroegtijdig detecteren en bespreekbaar maken.','Voldoende flexibiliteit om tijdelijke verminderde inzetbaarheid op te vangen.','Een organisatiecultuur waarin betrokkenheid, verantwoordelijkheid en welzijn elkaar versterken.'])+
        aandacht('Een gunstig resultaat vandaag biedt geen garantie voor morgen. Het behouden van lage verzuimcijfers vraagt blijvende aandacht voor leiderschap, werkorganisatie, psychosociaal welzijn en duurzame inzetbaarheid.')+
        acties(bullets('',['Borg succesvolle praktijken rond aanwezigheids- en terugkeerbeleid.','Documenteer en deel succesvolle aanpakken tussen teams en afdelingen.','Monitor verschillen tussen afdelingen om afwijkingen tijdig te detecteren.','Veranker verzuimpreventie structureel binnen het welzijns-, leiderschaps- en HR-beleid.']))+
        doel('Behoud van de huidige sterke positie met een kort verzuim onder 3,0%.')+
        monitoring(['Realtime verzuim- en welzijnsdata via het Storm-platform.','Continue ontwikkeling van leidinggevenden binnen het Culture of Care &amp; Capability-programma (COCC).','Ondersteuning van leidinggevende, HR en andere betrokken actoren via Casey AI.']),
      equal:
        analyse('Het kort verzuim binnen uw organisatie bevindt zich op het niveau van het sectorgemiddelde. Dit betekent dat uw organisatie presteert zoals verwacht binnen de huidige marktcontext. Er zijn geen directe signalen van verhoogd risico, maar er is tegelijk weinig buffer wanneer de verzuimdruk zou toenemen.')+
        bullets('Organisaties die rond het sectorgemiddelde presteren kenmerken zich doorgaans door:',['Een basisaanpak voor opvolging van afwezigheden en terugkeer naar het werk.','Leidinggevenden die verzuim opvolgen, maar niet altijd op een consistente manier.','Een beperkt aantal preventieve initiatieven rond welzijn en duurzame inzetbaarheid.','Verschillen tussen afdelingen die niet altijd systematisch worden opgevolgd.'])+
        aandacht('Een resultaat op benchmarkniveau biedt stabiliteit, maar geen concurrentieel voordeel. Zonder gerichte aandacht voor preventie en leiderschap bestaat het risico dat het kort verzuim geleidelijk stijgt en bijkomende kosten veroorzaakt. De grootste opportuniteit ligt niet in het terugdringen van een probleem, maar in het cre\u00ebren van een structurele voorsprong ten opzichte van de benchmark.')+
        acties(bullets('',['Versterk leidinggevenden in het vroegtijdig detecteren en bespreekbaar maken van signalen.','Verhoog het bewustzijn rond aanwezigheid, inzetbaarheid en terugkeer naar het werk.','Analyseer verschillen tussen afdelingen, teams en functies om lokale risico\u2019s zichtbaar te maken.','Veranker preventie en welzijn structureel binnen de dagelijkse werking.']))+
        doel('Behoud van het huidige niveau met een ambitie om door te groeien naar een kort verzuim onder het sectorgemiddelde van 3,3%.')+
        monitoring(['Maandelijkse verzuim- en welzijnsrapportering via het Storm-platform.','Monitoring van trends en afwijkingen op afdelingsniveau.','Automatische signalering wanneer het kort verzuim evolueert richting 4,0% of hoger.','Ondersteuning van leidinggevenden, medewerkers en HR via Casey AI.']),
      above:
        analyse('Het kort verzuim binnen uw organisatie ligt boven het sectorgemiddelde. Hoewel dit niet noodzakelijk wijst op een structureel probleem, vormt het wel een belangrijk signaal dat verdere aandacht verdient. Een verhoogd kort verzuim kan wijzen op onderliggende factoren die de aanwezigheid en inzetbaarheid van medewerkers be\u00efnvloeden. Indien deze signalen onvoldoende worden opgevolgd, bestaat het risico dat kortdurende afwezigheden evolueren naar frequenter of langduriger verzuim.')+
        bullets('Factoren die vaak samenhangen met een verhoogd kort verzuim zijn:',['Een verhoogde werkdruk of onevenwichtige taakverdeling.','Uitdagingen binnen teamdynamiek, leiderschap of werkklimaat.','Arbeidsomstandigheden die fysieke of mentale belasting verhogen.','Functie-, afdeling- of seizoensgebonden factoren kunnen bepaalde groepen disproportioneel be\u00efnvloeden.','Onvoldoende aandacht voor vroeg detectie en preventieve opvolging.'])+
        aandacht('Kort verzuim is vaak de eerste zichtbare indicator van bredere welzijns- of organisatievraagstukken. Een stijgende trend verdient daarom snelle analyse en gerichte opvolging, zodat onderliggende oorzaken tijdig kunnen worden aangepakt. Hoe vroeger signalen worden gedetecteerd, hoe groter de kans om verdere escalatie en bijkomende kosten te voorkomen.')+
        acties(bullets('',['Voer een gerichte analyse uit van de belangrijkste verzuimdrivers binnen de organisatie.','Versterk de gesprekstechnieken van leidinggevenden rond aanwezigheid, welzijn en inzetbaarheid.','Analyseer verschillen tussen afdelingen, functies en teams om lokale risico\u2019s te identificeren.','Verhoog de focus op preventie, vroegdetectie en duurzame inzetbaarheid.','Maak verzuim bespreekbaar vanuit ondersteuning en betrokkenheid, eerder dan vanuit controle.']))+
        doel('Verlaag het kort verzuim stapsgewijs naar het sectorgemiddelde van 3,3% binnen een termijn van 6 tot 12 maanden.')+
        monitoring(['Verzuimanalyses per afdeling, team en functie via het Storm-platform.','Monitoring van trends, frequentieverzuim en terugkerende patronen.','Vroegdetectie van risicosignalen en voortekenen via Casey AI.','Periodieke evaluatie van de impact van preventieve en leidinggevende interventies.'])
    },

    /* ───────── MIDDELLANG VERZUIM (benchmark 1,9%) ───────── */
    M:{
      under:
        analyse('Het middellang verzuim binnen uw organisatie ligt onder het sectorgemiddelde. Dit wijst op een sterke capaciteit om medewerkers succesvol te begeleiden tijdens afwezigheden van \u00e9\u00e9n tot twaalf maanden en hen op een duurzame manier terug te integreren in de organisatie.')+
        bullets('Organisaties die sterk presteren op middellang verzuim kenmerken zich doorgaans door:',['Een gestructureerde aanpak van verzuim- en re-integratiebegeleiding.','Tijdige opvolging van medewerkers tijdens hun afwezigheid.','Voldoende flexibiliteit in taken, rollen en werkorganisatie bij terugkeer.','Een nauwe samenwerking tussen leidinggevenden, HR en andere betrokken actoren.','Een cultuur waarin contact en betrokkenheid behouden blijven tijdens de afwezigheidsperiode.'])+
        aandacht('Een sterke prestatie op middellang verzuim is vaak het resultaat van consistente processen en kwalitatieve opvolging. Om dit voordeel te behouden, is het belangrijk om succesvolle werkwijzen niet afhankelijk te maken van individuele personen, maar structureel te verankeren binnen de organisatie. Daarnaast kunnen verschillen tussen afdelingen waardevolle inzichten bieden in welke aanpakken het meest effectief zijn.')+
        acties(bullets('',['Documenteer en standaardiseer verzuim- en re-integratieprocessen.','Versterk leidinggevenden, HR of andere betrokken actoren in hun rol binnen de begeleiding van middellang afwezige medewerkers.','Analyseer welke afdelingen of teams bovengemiddeld presteren en deel deze goede praktijken organisatiebreed.','Veranker de principes van Culture of Care &amp; Capability verder in de dagelijkse werking.','Gebruik data en inzichten om succesvolle aanpakken schaalbaar te maken binnen de volledige organisatie.']))+
        doel('Behoud van de huidige sterke positie met een ambitie om het middellang verzuim verder te optimaliseren richting 1,5% tot 1,7%.')+
        monitoring(['Verzuim- en re-integratieanalyses per afdeling via het Storm-platform.','Benchmarking van afdelingen en teams om succesvolle praktijken zichtbaar te maken.','Vroegdetectie van risico\u2019s en signalen die kunnen leiden tot langduriger afwezigheden via Casey AI.','Periodieke evaluatie van de effectiviteit van re-integratie- en begeleidingsprocessen.']),
      equal:
        analyse('Het middellang verzuim binnen uw organisatie bevindt zich op het niveau van het sectorgemiddelde. Hoewel dit resultaat op zich geen aanleiding geeft tot bezorgdheid, ligt net in deze verzuimcategorie vaak de grootste opportuniteit om zowel verzuimduur als verzuimkosten structureel te be\u00efnvloeden. Middellang verzuim vormt een cruciale fase in het verzuimproces. In deze periode wordt vaak bepaald of medewerkers succesvol terugkeren naar het werk, dan wel evolueren richting langdurige afwezigheid.')+
        bullets('Organisaties die beter presteren dan de benchmark onderscheiden zich doorgaans door:',['Een gestructureerde en consistente casemanagementaanpak.','Duidelijke eigenaarschap van verzuimdossiers.','Regelmatig en constructief contact tijdens de afwezigheidsperiode.','Tijdige evaluatie van arbeidspotentieel en re-integratiemogelijkheden.','Flexibiliteit in taken, rollen en werkorganisatie.'])+
        aandacht('Een benchmarkresultaat biedt stabiliteit, maar laat ruimte voor aanzienlijke verbetering. Kleine optimalisaties in de begeleiding van medewerkers kunnen een disproportioneel grote impact hebben op zowel de verzuimduur als de totale verzuimkost. De grootste winst ligt vaak niet in extra interventies, maar in een meer gestructureerde en consistente toepassing van bestaande processen.')+
        acties(
          group('1. Versterk het casemanagement',['Wijs \u00e9\u00e9n duidelijke casemanager (intern of extern) toe per verzuimdossier.','Evalueer vanaf de eerste weken systematisch het arbeidspotentieel en mogelijke terugkeerscenario\u2019s.','Zorg voor regelmatige contactmomenten gedurende de afwezigheidsperiode.','Faciliteer werkplek- en taakaanpassingen waar dit de terugkeer kan ondersteunen.'])+
          group('2. Versterk leiderschap en begeleiding',['Investeer in gerichte ontwikkeling van leidinggevenden via het Culture of Care &amp; Capability-programma.','Focus prioritair op afdelingen waar het middellang verzuim bovengemiddeld voorkomt.','Verhoog de kwaliteit van gesprekken rond inzetbaarheid, herstel en re-integratie. Betrek hierbij ook de verschillende actoren.'])+
          group('3. Maak datagedreven opvolging mogelijk',['Volg trends, doorlooptijden en risicoprofielen systematisch op.','Gebruik inzichten om interventies gericht in te zetten waar de impact het grootst is.','Combineer operationele opvolging met voorspellende inzichten.'])
        )+
        doel('Verlaag het middellang verzuim van 1,9% naar 1,5%. Deze verbetering kan leiden tot een aanzienlijke verlaging van de verzuimkost en een hogere duurzame inzetbaarheid van medewerkers.')+
        risico('Zonder gerichte opvolging bestaat het risico dat het middellang verzuim verder stijgt richting 2,3% \u00e0 2,5%, met een aanzienlijke impact op zowel operationele continu\u00efteit als totale verzuimkosten.')+
        monitoring(['Realtime verzuim- en re-integratiegegevens via het Storm-platform.','Predictieve signalering van risico\u2019s en escalaties via Casey AI.','Periodieke review van lopende verzuimdossiers en re-integratietrajecten.','Opvolging van resultaten per afdeling, team en leidinggevende.'])+
        prio('<b>Prioriteit 1.</b> Middellang verzuim biedt in de meeste organisaties de hoogste return on investment. Gerichte verbeteringen in deze categorie leveren vaak de snelste en meest duurzame impact op verzuimcijfers \u00e9n kostenbeheersing.'),
      above:
        analyse('Het middellang verzuim binnen uw organisatie ligt boven het sectorgemiddelde. Dit vormt een belangrijk aandachtspunt, aangezien deze verzuimcategorie vaak de overgang vormt tussen kortdurende afwezigheid en langdurig verzuim. Een verhoogd middellang verzuim wijst erop dat medewerkers minder snel terugkeren naar het werk dan verwacht of dat re-integratietrajecten onvoldoende effect hebben. Zonder gerichte interventies bestaat het risico dat een deel van deze dossiers evolueert naar langdurige afwezigheid, met een aanzienlijke impact op kosten, productiviteit en personeelsbeschikbaarheid.')+
        bullets('Organisaties die met verhoogd middellang verzuim geconfronteerd worden, herkennen vaak \u00e9\u00e9n of meerdere van onderstaande factoren:',['Onvoldoende gestructureerd casemanagement.','Onduidelijk eigenaarschap van verzuimdossiers.','Beperkte opvolging tijdens de afwezigheidsperiode.','Te late inschatting van arbeidspotentieel en re-integratiemogelijkheden.','Onvoldoende gebruik van taak-, uurrooster- of werkplekaanpassingen.','Leidinggevenden die onvoldoende ondersteund zijn in het begeleiden van afwezige medewerkers.'])+
        aandacht('Dit is de verzuimcategorie met de grootste impact op toekomstige langdurige afwezigheden. Elke maand die een medewerker langer afwezig blijft, verlaagt doorgaans de kans op een succesvolle en duurzame terugkeer. Vroege interventie, consistente opvolging en duidelijke regie zijn daarom cruciaal om escalatie naar langdurig verzuim te voorkomen.')+
        acties(
          group('1. Versterk de diagnosefase',['Analyseer systematisch waarom medewerkers langer afwezig blijven dan verwacht.','Breng drempels voor werkhervatting in kaart.','Evalueer welke werk- en taakaanpassingen reeds werden onderzocht of toegepast.','Identificeer terugkerende patronen per afdeling, functie of leidinggevende.'])+
          group('2. Structureer het casemanagement',['Wijs \u00e9\u00e9n duidelijke casemanager (intern of extern) toe per verzuimdossier.','Evalueer actief het arbeidspotentieel en mogelijke terugkeerscenario\u2019s.','Zorg voor regelmatige contactmomenten gedurende de volledige afwezigheidsperiode.','Maak taak-, werkplek- en uurroosteraanpassingen een vast onderdeel van elk re-integratietraject.'])+
          group('3. Versterk leiderschap en begeleiding',['Investeer prioritair in het Culture of Care &amp; Capability-programma.','Ondersteun leidinggevenden in het voeren van verbindende gesprekken rond inzetbaarheid en werkhervatting.','Maak het onderscheid duidelijk tussen ondersteunen, begeleiden en ongewenste druk uitoefenen.'])+
          group('4. Stuur op data en vroegdetectie',['Monitor verzuimtrends op wekelijkse basis.','Detecteer vroegtijdig signalen van escalatie richting langdurig verzuim.','Evalueer de effectiviteit van interventies systematisch en stuur bij waar nodig.'])
        )+
        doel('Verlaag het middellang verzuim naar het sectorgemiddelde van 1,9%. Deze verbetering kan leiden tot een aanzienlijke kostenbesparing en een merkbare afname van het risico op langdurige uitval.')+
        risico('Indien geen gerichte maatregelen worden genomen, bestaat het risico dat het middellang verzuim verder stijgt en een groter aandeel medewerkers doorstroomt naar langdurige afwezigheid. Dit veroorzaakt niet alleen hogere verzuimkosten, maar verhoogt ook de druk op teams, leidinggevenden en operationele processen.')+
        monitoring(['Wekelijkse opvolging van verzuimcijfers en trends via het Storm-platform.','Vroegdetectie en risico-alerting via Casey AI.','Periodieke reviews van dossiers op 30-, 60- en 90-dagenbasis.','Opvolging van resultaten per afdeling, functie en leidinggevende.'])+
        prio('<b>Prioriteit 1 \u2014 kritisch.</b> Middellang verzuim is \u00e9\u00e9n van de sterkste voorspellers van toekomstig langdurig verzuim. Een gerichte aanpak in deze fase levert doorgaans de hoogste impact op, zowel op verzuimreductie als op kostenbeheersing. Daarom verdient deze categorie onmiddellijke en structurele aandacht van HR, leidinggevenden en management.')
    },

    /* ───────── LANGDURIG VERZUIM (benchmark 1,4%) ───────── */
    L:{
      under:
        analyse('Het langdurig verzuim binnen uw organisatie ligt onder het sectorgemiddelde. Dit wijst op een sterke beheersing van langdurige afwezigheden en een effectieve aanpak om te voorkomen dat medewerkers langdurig uitvallen.')+
        bullets('Organisaties die duurzaam beter presteren op langdurig verzuim kenmerken zich doorgaans door:',['Een sterke opvolging van middellange verzuimdossiers en re-integratietrajecten.','Voldoende flexibiliteit in functies, taken en werkorganisatie.','Een cultuur waarin duurzame inzetbaarheid centraal staat.','Een goede samenwerking tussen leidinggevenden, HR, preventie en externe partners.','Tijdige ondersteuning van medewerkers voordat problemen escaleren naar langdurige uitval.'])+
        aandacht('Een laag langdurig verzuim is vaak het resultaat van jarenlang opgebouwde processen en een sterke preventieve aanpak. Het behoud van deze positie vraagt blijvende aandacht voor re-integratie, werkbaar werk en vroegtijdige interventie. Daarnaast blijft het belangrijk om medewerkers die reeds langdurig afwezig zijn actief te begeleiden. De grootste kans op succesvolle werkhervatting bevindt zich doorgaans in het eerste jaar van afwezigheid.')+
        acties(bullets('',['Blijf investeren in de succesvolle aanpak van middellang verzuim om doorstroom naar langdurige afwezigheid te voorkomen.','Voorzie individuele re-integratietrajecten voor medewerkers die reeds langdurig afwezig zijn.','Onderzoek mogelijkheden voor job crafting, aangepaste taken en gefaseerde werkhervatting.','Evalueer alternatieve rollen of werkvormen waar een terugkeer naar de oorspronkelijke functie niet haalbaar blijkt.','Werk samen met externe partners om duurzame terugkeertrajecten maximaal te ondersteunen.']))+
        doelen(['Behoud van het langdurig verzuim onder het sectorgemiddelde van 1,4%.','Verhoog de reactivatiegraad van bestaande langdurige dossiers.','Voorkom dat middellang verzuim evolueert naar langdurige afwezigheid.'])+
        monitoring(['Analyse van dossierduur, werkhervattingen en taakaanpassingen via het Storm-platform.','Opvolging van individuele actieplannen en re-integratietrajecten.','Monitoring van de doorstroom van middellang naar langdurig verzuim.','Evaluatie van uitstroom- en exitpatronen om structurele oorzaken beter te begrijpen.','Vroegdetectie van risico\u2019s via Casey AI.'])+
        prio('<b>Prioriteit 3 \u2014 consolideren en behouden.</b> De resultaten tonen aan dat de huidige aanpak effectief werkt. De focus ligt daarom niet op ingrijpende correcties, maar op het behouden van succesvolle praktijken, het optimaliseren van bestaande langdurige dossiers en het voorkomen van toekomstige instroom vanuit middellang verzuim.'),
      equal:
        analyse('Het langdurig verzuim binnen uw organisatie bevindt zich op het niveau van het sectorgemiddelde. Hoewel dit resultaat geen directe aanleiding geeft tot bezorgdheid, verdient deze verzuimcategorie bijzondere aandacht vanwege haar grote impact op kosten, inzetbaarheid en personeelsbeschikbaarheid. Langdurig verzuim is vaak het eindresultaat van een proces dat maanden eerder begint. Hoe langer een medewerker afwezig blijft, hoe kleiner doorgaans de kans op een succesvolle en duurzame terugkeer naar het werk. Organisaties die langdurig verzuim onder controle houden, investeren daarom niet alleen in begeleiding van bestaande dossiers, maar vooral in het voorkomen van nieuwe instroom.')+
        aandacht('De eerste twaalf maanden van langdurige afwezigheid vormen doorgaans de meest cruciale periode voor re-integratie. Actieve begeleiding, aangepaste werkmogelijkheden en een realistische terugkeerstrategie kunnen in deze fase nog een aanzienlijk verschil maken. Daarnaast blijft middellang verzuim de belangrijkste voorspeller van toekomstige langdurige uitval. Een sterke aanpak van middellange dossiers vormt daarom de meest effectieve vorm van preventie.')+
        acties(
          group('1. Versterk de aanpak van bestaande langdurige dossiers',['Voorzie actieve opvolging van medewerkers in langdurige afwezigheid. Stel hiervoor een casemanager aan (intern of extern).','Onderzoek mogelijkheden voor job crafting en aangepaste functies.','Faciliteer deeltijdse of gefaseerde werkhervatting waar mogelijk.','Evalueer alternatieve taken, rollen of werkvormen.','Maak gebruik van externe ondersteuning en gespecialiseerde begeleiding wanneer dit de terugkeer kan versnellen.'])+
          group('2. Voorkom instroom vanuit middellang verzuim',['Versterk de opvolging van medewerkers in de middellange verzuimfase.','Detecteer vroegtijdig dossiers met verhoogd risico op langdurige uitval.','Zet sneller in op arbeidspotentieel, taakaanpassingen en re-integratiemogelijkheden.','Veranker eigenaarschap en opvolging binnen het casemanagementproces.'])
        )+
        doelen(['Behoud van het langdurig verzuim op of onder het sectorgemiddelde van 1,4%.','Verhoog de reactivatie van bestaande langdurige dossiers.','Voorkom bijkomende instroom vanuit middellang verzuim.'])+
        monitoring(['Analyse van dossierduur en verzuimtrends via het Storm-platform.','Opvolging van individuele actieplannen en re-integratietrajecten.','Monitoring van de doorstroom van middellang naar langdurig verzuim.','Evaluatie van afgesloten dossiers en exit-analyses om leerpunten te identificeren.','Vroegdetectie van risicosignalen via Casey AI.'])+
        prio('<b>Prioriteit 2 \u2014 actieve beheersing.</b> Hoewel het langdurig verzuim zich op benchmarkniveau bevindt, vraagt deze categorie blijvende aandacht. De grootste impact wordt gerealiseerd door bestaande dossiers actief te begeleiden \u00e9n te voorkomen dat medewerkers vanuit middellang verzuim doorstromen naar langdurige afwezigheid. Hier ligt de sleutel tot duurzame beheersing van toekomstige verzuimkosten.'),
      above:
        analyse('Het langdurig verzuim binnen uw organisatie ligt boven het sectorgemiddelde. Dit vormt een belangrijke uitdaging, aangezien langdurige afwezigheden doorgaans de grootste impact hebben op verzuimkosten, productiviteit, personeelsplanning en operationele continu\u00efteit. Een verhoogd langdurig verzuim ontstaat zelden plots. In de meeste gevallen is het het resultaat van onderliggende processen die onvoldoende worden onderbroken tijdens eerdere verzuimfases. Daarom is het essentieel om niet alleen de huidige langdurige dossiers te beheren, maar ook de oorzaken van de instroom grondig te analyseren.')+
        bullets('Organisaties met verhoogd langdurig verzuim worden vaak geconfronteerd met \u00e9\u00e9n of beide onderstaande situaties:',['Onvoldoende beheersing van middellang verzuim, waardoor medewerkers doorstromen naar langdurige afwezigheid.','Complexe langdurige dossiers waarbij medische, psychosociale of organisatorische factoren een succesvolle terugkeer bemoeilijken.'])+
        aandacht('De sterkste voorspeller van toekomstig langdurig verzuim is een verhoogd middellang verzuim. Daarom ligt de grootste hefboom vaak niet in het beheren van bestaande langdurige dossiers, maar in het voorkomen van nieuwe instroom. Tegelijkertijd blijft snelle actie cruciaal bij medewerkers die reeds langdurig afwezig zijn. De kans op een succesvolle werkhervatting neemt doorgaans af naarmate de afwezigheidsduur toeneemt.')+
        acties(
          group('Route 1 \u2014 Versterk de aanpak van middellang verzuim',['Analyseer de doorstroom van middellang naar langdurig verzuim.','Versterk casemanagement en dossieropvolging.','Faciliteer sneller taak-, functie- en werkplekaanpassingen.','Detecteer dossiers met verhoogd risico op escalatie.','Veranker eigenaarschap en opvolging binnen het volledige re-integratieproces.'],'Dit vormt de belangrijkste prioriteit.')+
          group('Route 2 \u2014 Activeer bestaande langdurige dossiers',['Analyseer de belangrijkste oorzaken van langdurige afwezigheid.','Prioriteer dossiers binnen het eerste jaar van afwezigheid.','Onderzoek mogelijkheden voor job crafting en alternatieve functies.','Faciliteer gefaseerde of deeltijdse werkhervatting waar haalbaar.','Zet externe expertise en gespecialiseerde begeleiding gericht in.'])
        )+
        doel('Verlaag het langdurig verzuim naar het sectorgemiddelde van 1,4% binnen een termijn van 6 tot 12 maanden. Deze verbetering kan een aanzienlijke impact hebben op zowel verzuimkosten als personeelsbeschikbaarheid.')+
        risico('Indien geen gerichte maatregelen worden genomen, bestaat het risico op verdere stijging van het langdurig verzuim. Dit kan leiden tot een negatieve spiraal van hogere kosten, toenemende werkdruk, meer vervangingsnoden en bijkomende instroom vanuit middellang verzuim.')+
        monitoring(['Wekelijkse opvolging van langdurige dossiers via het Storm-platform.','Analyse van de doorstroom van middellang naar langdurig verzuim.','Monitoring van dossierduur, re-integratiekansen en werkhervattingen.','Vroegdetectie van risicosignalen via Casey AI.','Periodieke case reviews en evaluatie van lopende interventies.'])+
        prio('<b>Prioriteit 1 \u2014 urgent.</b> Een verhoogd langdurig verzuim vraagt onmiddellijke aandacht van HR, leidinggevenden en management. De combinatie van een sterke middellang-aanpak en een actieve re-integratiestrategie voor bestaande dossiers biedt de grootste kans op duurzame verbetering en kostenreductie.')
    }
  };
})();
